name = "stm32f0x2_hal"
description = "Drivers (maybe) and HAL for stm32f0x2 mcu family"
version = "0.0.0"

authors = ["Marc Poulhiès"]
maintainers = ["Marc Poulhiès <dkm@kataplop.net>"]
maintainers-logins = ["dkm"]

[[depends-on]]  # Added by alr
cortex_m = "^0.1"
#cortex_m = { url="https://github.com/Fabien-Chouteau/cortex-m.git" }
hal = "^0.1"
##usb_embedded = { path='../usb_embedded' }
usb_embedded = "~0.2"
gnat_arm_elf = "^11.2"

[configuration.variables]
Use_Startup = {type = "Boolean", default = true}

